### ISSUE TITLE
What do you think in case we expect you to work on some more things in `Optional features` section?

### ISSUE THREAD

**Issue by luongvo** [cuonghuynhvan/nimble-surveys#10]
- For must to have features: I can't find this function in the current build, not sure if you missed it for a reason. It's just a small criteria but the careful habit is also a thing we're looking for from our candidates.
![image](https://user-images.githubusercontent.com/16315358/100427498-1ee5cf80-30c5-11eb-96c4-6fc9506187ac.png)

- For nice to have features `Optional features`: If you have some spare time and want to go the extra mile 💪, you can work on these optional requirements, that could help us so much on our process to validate you and think that you totally fit our team.

**Comment by cuonghuynhvan** [comment]
```
For must to have features: I can't find this function in the current build, not sure if you missed it for a reason. It's just a small criteria but the careful habit is also a thing we're looking for from our candidates.
```
There is a difference between the requirement and the design. As you can see in the screenshot below that there is a screen when the user clicks on a survey item or arrow button and that screen contains the "Take Survey" button, not the home screen. In the real project, I always confirm this issue with the PO or BA. Because it was at the weekend when I worked on this project, so I must took a choice.
![screenshot](https://user-images.githubusercontent.com/7866660/100538387-09f27300-3262-11eb-9104-c6f892376460.png)
```
For nice to have features Optional features: If you have some spare time and want to go the extra mile 💪, you can work on these optional requirements, that could help us so much on our process to validate you and think that you totally fit our team.
```
Yes, I would love to go the extra mile if I have some spare time.

**Comment by luongvo** [comment]
@cuonghuynhvan okay, we will make an internal discussion to remove that conflict between the requirement and the design. Thanks for reporting that out.
